vich_uploader:
    db_driver: orm
    # Prise en charge de php
    metadata:
        type: attribute

    mappings:
        home:
            uri_prefix: /images/home
            upload_destination: '%kernel.project_dir%/public/images/home'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        services:
            uri_prefix: /images/services
            upload_destination: '%kernel.project_dir%/public/images/services'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        carousel:
            uri_prefix: /images/carousel
            upload_destination: '%kernel.project_dir%/public/images/carousel'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
